[package]
name = "puteron-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
structre = "0.2"
serde = { version = "1", features = ["derive"] }
schemars = { version = "0.8", features = ["chrono"] }
chrono = { version = "0.4", features = ["serde"] }
